# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.0' # Set a specific iOS version for Core ML compatibility
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Define shared pods for both main app and test targets
def shared_pods
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => flipper_config,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
end

target 'monGARS' do
  shared_pods

  target 'monGARSTests' do
    inherit! :search_paths
    shared_pods
    # Pods for testing can be added here
  end

  post_install do |installer|
    # Get config from shared_pods function - we need to call use_native_modules! again
    config = use_native_modules!
    
    react_native_post_install(
      installer,
      config[:reactNativePath],
      # Set mac_catalyst_enabled to false to avoid build issues
      :mac_catalyst_enabled => false
    )
    
    # Fix for Core ML compilation and Xcode 15+
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['ENABLE_COREML_FRAMEWORK'] = 'YES'
        config.build_settings['OTHER_CFLAGS'] = '$(inherited) -DCORE_ML_ENABLED'
        config.build_settings['ENABLE_BITCODE'] = 'YES'
        
        if config.name == 'Release'
          config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '3'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
        end
        
        config.build_settings['DEVELOPMENT_TEAM'] = ''
        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        
        if ENV['RCT_NEW_ARCH_ENABLED'] == '1'
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -DRCT_NEW_ARCH_ENABLED'
          config.build_settings['OTHER_CFLAGS'] = '$(inherited) -DRCT_NEW_ARCH_ENABLED'
        end
      end
    end
  end
end